[package]
name = "battery-stats"
version = "0.1.0"
authors = ["Murad <muradkarammaev@gmail.com>"]
edition = "2018"

[[bin]]
name = "read-stats"
path = "src/read-stats/bin/main.rs"

[[bin]]
name = "process-stats"
path = "src/process-stats/bin/main.rs"

[dependencies]
csv = "1.1"
